SecureApiGateway/secure-api-gateway-parent

pom.xml

Part of https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/4

4: Use current version of spring

---

README.md
pom.xml

Also adds a read me and some more 3rd party dependencies

4: Use secure banking BOM and spring BOM

---

.github/workflows/check-build.yml

Checks the build integrity on creation of a pr or a push to master. i.e.
when a PR is create, and when code is merged into master

Create check build github action

---

.github/workflows/release.yml

4: Publish to artifactory when a release is made

---

CHANGELOG.md
pom.xml

- Ensured JUnit 4 isn't being pulled in by spring-boot-starter-test
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/27

27: Exclude JUnit 4

---

CHANGELOG.md
pom.xml

Specify version of git-commit-id-plugin
Specify locale for build-helper-plugin

4: Remove some warnings from child builds

---

CHANGELOG.md
pom.xml

Add spring-cloud-starter-sleuth
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/33

33: Add spring-cloud-starter-sleuth

---

CHANGELOG.md
pom.xml

Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/61

61: spring-cloud-config-serve dependency

---

CHANGELOG.md
pom.xml

Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/61

61: spring-cloud-config-client dependency

---

CHANGELOG.md
pom.xml

Switched from jib to dockerfile maven plugin

66 - Switched from jib to dockerfile maven plugin

---

CHANGELOG.md
pom.xml

Add docker related files to licence header exclusion list
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66

66 - Add docker related files to licence header exclusion list

---

CHANGELOG.md
pom.xml

- Upgrade modelmapper version to 2.4.4
- Upgrade version to 1.0.2-SNAPSHOT
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/90

90: account access and domestic payment journeys

---

CHANGELOG.md
pom.xml

- Added new apache httpclient to support patch requests
- Added commons-lang3
- Version updated to 1.0.4

Dependencies:

---

pom.xml

- Fix dependencies to inject resources for test purposes
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/590

590: file payment file validations dependencies

---

README.md
pom.xml

- Updated pom maven descriptorgroup and artifact Ids
- Update readme file 
Issue: https://github.com/secureapigateway/secureapigateway/issues/835

835: rename repository

---

.github/ISSUE_TEMPLATE/config.yml
README.md
pom.xml

- Renamed artifact groupId to `com.forgerock.sapi.gateway`
Issue: https://github.com/secureapigateway/secureapigateway/issues/835

835: rename repository (groupId)

---

pom.xml

- Udpated developer version to 0.9.0
Issue: https://github.com/secureapigateway/secureapigateway/issues/835

835: update snapshot version

---

.github/dependabot.yml

Enable dependabot version update PRs for maven

Enable dependabot version upgrade PRs

---

README.md
pom.xml

- Upgrade version to 2.0.0
- Fix typo in readme file
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099

1099: upgrade version

---

.github/workflows/merge-master.yml
.github/workflows/pr.yml
.github/workflows/release-prepare.yml
.github/workflows/release-publish-docker.yml
.github/workflows/release-publish-java.yml
pom.xml

https://github.com/SecureApiGateway/SecureApiGateway/issues/1139

1139: Updating Java version to 17 

---

pom.xml

Matching the Spring Boot version.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1235

1235: Updating Spring Boot Maven plugin to 3.2.1

---

.github/workflows/release-publish-docker.yml

Change docker repo paths for new Artifact Registry
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987

987: Artifact Registry Migration

---

.github/workflows/release-publish-docker.yml

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987

987: Fix workflow for docker using var for GAR repo

---

.github/workflows/release-publish-docker.yml

New command needed for docker auth & remove outdated versions of actions
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987

987: Fix docker workflow for Artifact Registry

---

.github/workflows/merge-master.yml
.github/workflows/pr.yml
.github/workflows/release-prepare.yml
.github/workflows/release-publish-docker.yml
.github/workflows/release-publish-java.yml

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1257

1257: Update java action and distribution

---

.github/workflows/merge-master.yml
.github/workflows/pr.yml
.github/workflows/release-prepare-no-maven.yml
.github/workflows/release-prepare.yml
.github/workflows/release-publish-docker.yml
.github/workflows/release-publish-draft-and-pr.yml
.github/workflows/release-publish-helm.yml
.github/workflows/release-publish-java.yml

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264

1264: Update actions that have deprecations

---

.github/workflows/release-prepare.yml
pom.xml

Add in the PAT Token for fropenbanking
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1263

1260: Changes to PR workflows during release

---

.github/workflows/release-prepare-no-maven.yml
.github/workflows/release.yml

Commit directly to master instead of having a PR to approve and merge
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1260

1260: Investigate PR runs for GitHub user

---

pom.xml

Merge ob-v4 -> Master to combine V4 work for release
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1566

1566: Revert Repos back to master|main
