SecureApiGateway/secure-api-gateway-parent

README.md, pom.xml
After testing, and also getting JAVA_HOME set to the right JDK in
/etc/profile.d/jdk.sh (on Ubuntu 20.04) then I could be much more hands
off with regard to specifying the java version. I no longer need to have
the maven-complier-plugin specify which javac compiler to use!
=> 4: Refactor how Java 14 is specified

pom.xml
While addressing PR comments for https://github.com/SecureBankingAcceleratorToolkit/securebanking-common/pull/1
I have moved some of the dependencies that were being managed in
securebanking-common-openbanking-uk-datamodel into the parent pom
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/12
=> 12: Manage securebanking-common dependencies

pom.xml
The JAVADOC_STYLE is more familiar and I can see no benefit to having
the license placed after the package declaration in the .java file.
=> Places license at top of file using JAVADOC_STYLE

.github/workflows/check-build.yml, .github/workflows/merge-master.yml
Separated the action out. Now have merge-master action and check-build.
Merge-master action will publish a SNAPSHOT release when merging to
master.
Full releases must be managed locally to perform the release and then
when a release is created in github the release artifact will be
pubished.
=> 4: Publish SNAPSHOT release on merge to master

.github/workflows/check-build.yml, .github/workflows/merge-master.yml, pom.xml
In trying to exclude junit4 from spring-boot-starter-test I was
overriding the import from the spring-boot-dependencies bom and hiding
the version!
=> 4: Update snapshots and remove bad spring-boot-starter-test

CHANGELOG.md, pom.xml
This PR introduces the following:
- The required dependencies for securebanking-openbanking-aspsp-simulator
- Strips out JUnit 4 dependencies and enforces it with the maven enforcer plugin
- Grouped dependency versions by type
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/27
=> 27: Add dependencies for aspsp-simulator

CHANGELOG.md, pom.xml
Wiremock dependency for tests
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
=> 58: Add Wiremock

.gitignore, pom.xml
each microservice will have a `_infra` folder containing the helm chart. need to add the license exclusion from this folder
=> add _infra to the license exclude pom

pom.xml
- Execute the license format goal as part of the process-sources lifecycle, to automatically add/update the license
- Change license comment style to SLASHSTAR (/*) from JAVADOC (/**)
- Update copyright year range to include 2022
- Bumping version to 1.0.5-SNAPSHOT
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/458
=> 458: Changes to the license-maven-plugin configuration

pom.xml
This reverts commit 3a161aaca8b7f53bc5c761371e1db1fecc613bfc.
The jackson.version property is also used by jackson-annotations, version 2.12.7.1 does not exist.
=> Revert "Bump jackson-databind from 2.11.3 to 2.12.7.1 (#45)"

.github/workflows/merge-master.yml
- Fix error in merge-master workflow change `with` to `env` to inject properly the environment maven settings
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/812
=> 812: release actions fix merge master

pom.xml
Switching to jdk18on (JDK 1.8+) flavour of bouncy castle libraries and updating them to version 1.77
jdk15on (JDK 1.5+) flavour is no longer being developed.
This will resolve the dependabot PR: https://github.com/SecureApiGateway/secure-api-gateway-parent/pull/51 , it is unable to update to v1.77 as the artifact name is changing.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1219
=> 1219: Updating to bouncy castle version 1.77

pom.xml
Updating Spring Boot dependency to 2.7.18
Updating embedded MongoDB (de.flapdoodle.embed.mongo dependency) used for testing to 4.12.0, as required by Spring Boot update.
Updating parent version to 2.3.0-SNAPSHOT.
Removing Spring Cloud dependencies as these are no longer used.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1234
=> 1234: Updating Spring Boot to 2.7.18

pom.xml
Removing the following:
- logstash-logback-encoder
- org.glassfish.jersey
- springfox-swagger-ui
- inject-resources-core
- jmockdata
- wiremock
https://github.com/SecureApiGateway/SecureApiGateway/issues/1238
=> 1238: Removing unused dependencies

pom.xml
Setting: copyright-current-year to 2024
Updating copyright header of pom.xml file.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1238
=> 1238: Update copyright current year

pom.xml
springfox is not being used, it is only required as it transitively pulls in the swagger-annotations dependency required by our code.
Removing springfox and adding swagger-annotations.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1244
=> 1244: Remove springfox dependency

pom.xml
Major version update of Spring to 3.2.1
Changes:
- javax.validation changes to jakarta.validation
- update hibernate version (which implements jakarta.validation) to version 8.0.1
- httpclient version 5.2.3
- de.flapdoodle.embed.mongo.spring27x dependency replaced with de.flapdoodle.embed.mongo.spring3x
- Enable compiler parameter name retention
- Required by the RS for certain reflection based mapping
- https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention
=> 1235: Upgrade Spring to 3.2.1

pom.xml
Adding dependency on io.swagger.core.v3:swagger-annotations as updated generator version produces code which uses this dependency.
Existing io.swagger:swagger-annotations dependency has been kept whilst we migrate code to use the new generator.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
=> 1243: Updating openapi generator to 7.2.0

.github/workflows/release-prepare.yml
Stop the mvn command pushing commits as it's done on the next step, hopefully get around the branch merge strategy issue
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1260
=> 1260: Investigate PR runs for GitHub user

pom.xml
Manually update the parent pom property representing the current year, so that downstream project license checks succeed (during `mvn license:check` part of build).
Ideally, this should be picked up automatically from the current date/timestamp.
TODO(later): Maybe see - auto-set property based on timestamp:
https://stackoverflow.com/questions/39307133/maven-property-for-current-year
=> Update parent pom license checks current year to 2025
